dataset_name: "sarakarimi30/PlantMap"
finetune_checkpoint: True
dropout: 0.0
pretrained_checkpoint: "CLIP_classifier_ImpEquator_SGD_classifier_best_model-epoch=05-val_accuracy=91.05.ckpt"
model_type: "Classifier"
freeze_CLIP: True
